;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sentence
        beginning-of-buffer
        beginning-of-visual-line
        end-of-visual-line
        forward-sentence
        kill-visual-line
        query-replace
        ))

(setq mc/cmds-to-run-once
      '(
        ))
